version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/progresql/data
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=poolsystem
      - POSTGRES_PASSWORD=poolsystem
      - POSTGRES_DB=poolsystem_dev
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on: db
    volumes:
      - .:/usr/src/code
      - /app/node_modules
    env_file:
      - ./poolsystem/.env
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data: