version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: |
            pipenv run python manage.py test
          environment:
            DEBUG: 1
            SECRET_KEY: foo
            DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
            SQL_ENGINE: django.db.backends.postgresql
            SQL_DATABASE: poolsystem_dev
            SQL_USER: poolsystem
            SQL_PASSWORD: poolsystem
            SQL_HOST: db
            SQL_PORT: 5432
            DATABASE: postgres
      - store_artifacts:
          path: test-reports/
          destination: python_app
