# Generated by Django 3.0.2 on 2020-02-02 11:45

from django.conf import settings
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    superuser = get_user_model()(
        is_active=True,
        is_superuser=True,
        is_staff=True,
        username='admin',
        email='admin@admin.com',
    )
    superuser.set_password('admin')
    superuser.save()


def create_data(apps, schema_editor):
    user = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    poll = apps.get_model('polls', 'Poll')
    poll_option = apps.get_model('polls', 'PollOption')
    vote = apps.get_model('polls', 'Vote')

    user_1 = user.objects.create(username='user1',
                                 email='user1@example.com',
                                 password=make_password('user1'))

    user_2 = user.objects.create(username='user2',
                                 email='user2@example.com',
                                 password=make_password('user2'))

    poll_1 = poll(title="title of the poll_1",
                  descriptin="descriptin of the poll_1",
                  question="question of the poll_1",
                  owner=user_1)
    poll_1.save()

    poll_2 = poll(title="title of the poll_2",
                  descriptin="descriptin of the poll_2",
                  question="question of the poll_2",
                  owner=user_2)
    poll_2.save()

    poll_option_1 = poll_option(text="option_1 for poll_1",
                                poll=poll_1)
    poll_option_1.save()

    poll_option_2 = poll_option(text="option_2 for poll_1",
                                poll=poll_1)
    poll_option_2.save()

    poll_option_3 = poll_option(text="option_3 for poll_2",
                                poll=poll_2)
    poll_option_3.save()

    vote_1 = vote(user=user_1,
                  poll_option=poll_option_1)
    vote_1.save()

    vote_2 = vote(user=user_2,
                  poll_option=poll_option_2)
    vote_2.save()

    vote_3 = vote(user=user_1,
                  poll_option=poll_option_3)
    vote_3.save()

    vote_4 = vote(user=user_2,
                  poll_option=poll_option_1)
    vote_4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_data),
    ]
